import { currentConfigVersion, type Config } from "./config";

const defaultConfig: Config = {
	version: currentConfigVersion,
	options: {
		trigger: "!",
		storageMethod: "sync",
		ignoredSearchDomains: [],
		ignoreBangCase: false,
		sortBangsAlpha: false,
		querySeparator: "",
	},
	bangs: [
		{
			keyword: "a",
			alias: "",
			defaultUrl: "",
			urls: ["https://amazon.co.uk/s?k=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "e",
			alias: "",
			defaultUrl: "",
			urls: ["https://www.ebay.co.uk/sch/i.html?_nkw=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "ea",
			alias: "",
			defaultUrl: "",
			urls: [
				"https://amazon.co.uk/s?k=%s",
				"https://www.ebay.co.uk/sch/i.html?_nkw=%s",
			],
			dontEncodeQuery: false,
		},
		{
			keyword: "et",
			alias: "",
			defaultUrl: "",
			urls: ["https://www.etsy.com/uk/search?q=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "t",
			alias: "",
			defaultUrl: "",
			urls: ["https://www.twitch.tv/search?term=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "y",
			alias: "",
			defaultUrl: "",
			urls: ["https://www.youtube.com/results?search_query=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "av",
			alias: "",
			defaultUrl: "",
			urls: ["https://amazon.co.uk/s?k=%s&i=instant-video"],
			dontEncodeQuery: false,
		},
		{
			keyword: "n",
			alias: "",
			defaultUrl: "",
			urls: ["https://www.netflix.com/search?q=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "g",
			alias: "",
			defaultUrl: "",
			urls: ["https://www.google.com/search?q=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "b",
			alias: "",
			defaultUrl: "",
			urls: ["https://www.bing.com/search?q=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "d",
			alias: "",
			defaultUrl: "",
			urls: ["https://duckduckgo.com/?q=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "q",
			alias: "",
			defaultUrl: "",
			urls: ["https://www.qwant.com/?q=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "m",
			alias: "",
			defaultUrl: "",
			urls: ["https://www.google.com/maps/search/%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "r",
			alias: "",
			defaultUrl: "",
			urls: ["https://www.google.com/search?q=site%3Areddit.com+%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "git",
			alias: "",
			defaultUrl: "",
			urls: ["https://github.com/search?q=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "mdn",
			alias: "",
			defaultUrl: "",
			urls: ["https://developer.mozilla.org/en-US/search?q=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "pypi",
			alias: "",
			defaultUrl: "",
			urls: ["https://pypi.org/search/?q=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "npm",
			alias: "",
			defaultUrl: "",
			urls: ["https://www.npmjs.com/search?q=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "so",
			alias: "",
			defaultUrl: "",
			urls: ["https://stackoverflow.com/search?q=%s"],
			dontEncodeQuery: false,
		},
		{
			keyword: "w",
			alias: "",
			defaultUrl: "",
			urls: ["https://www.wolframalpha.com/input/?i=%s"],
			dontEncodeQuery: false,
		},
	],
};

export default defaultConfig;
